CREATE TABLE IF NOT EXISTS "manager"(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255),
    department VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS "user"(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255),
    mobile VARCHAR(255),
    pan VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT NULL,
    isActive BOOLEAN DEFAULT TRUE,
    managerId INTEGER,
    FOREIGN KEY (managerId) REFERENCES "manager"(id)
);